{% set version = "5.5.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dtwclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dtwclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dtwclust/dtwclust_{{ version }}.tar.gz
  sha256: c3d8ac0df9d01080d716bfa96d6517adb4aea2ad80910e387faff1cc4b942cbb

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - {{ posix }}findutils         # [win]
  host:
    - r-base
    - r-matrix
    - r-rspectra
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppparallel >=4.4.0
    - r-rcppthread
    - r-bigmemory
    - r-clue
    - r-cluster
    - r-dplyr
    - r-dtw
    - r-flexclust
    - r-foreach
    - r-ggplot2
    - r-ggrepel
    - r-nloptr
    - r-proxy >=0.4_16
    - r-reshape2
    - r-shiny
    - r-shinyjs
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-rspectra
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppparallel >=4.4.0
    - r-rcppthread
    - r-bigmemory
    - r-clue
    - r-cluster
    - r-dplyr
    - r-dtw
    - r-flexclust
    - r-foreach
    - r-ggplot2
    - r-ggrepel
    - r-nloptr
    - r-proxy >=0.4_16
    - r-reshape2
    - r-shiny
    - r-shinyjs

test:
  commands:
    - $R -e "library('dtwclust')"           # [not win]
    - "\"%R%\" -e \"library('dtwclust')\""  # [win]

about:
  home: https://github.com/asardaes/dtwclust
  license: GPL-3
  summary: Time series clustering along with optimized techniques related to the Dynamic Time Warping distance and its corresponding lower bounds. Implementations of partitional, hierarchical, fuzzy, k-Shape and TADPole clustering are available. Functionality can be easily extended with custom distance measures and centroid
    definitions. Implementations of DTW barycenter averaging, a distance based on global alignment kernels, and the soft-DTW distance and centroid routines are also provided.  All included distance functions have custom loops optimized for the  calculation of cross-distance matrices, including parallelization support. Several
    cluster validity indices are included.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: dtwclust
# Type: Package
# Title: Time Series Clustering Along with Optimizations for the Dynamic Time Warping Distance
# Description: Time series clustering along with optimized techniques related to the Dynamic Time Warping distance and its corresponding lower bounds. Implementations of partitional, hierarchical, fuzzy, k-Shape and TADPole clustering are available. Functionality can be easily extended with custom distance measures and centroid definitions. Implementations of DTW barycenter averaging, a distance based on global alignment kernels, and the soft-DTW distance and centroid routines are also provided.  All included distance functions have custom loops optimized for the  calculation of cross-distance matrices, including parallelization support. Several cluster validity indices are included.
# Version: 5.5.4
# Depends: R (>= 3.2.0), methods, proxy (>= 0.4-16), dtw
# Imports: parallel, stats, utils, bigmemory, clue, cluster, dplyr, flexclust, foreach, ggplot2, ggrepel, Matrix, nloptr, RSpectra, Rcpp, RcppParallel (>= 4.4.0), reshape2, shiny, shinyjs
# LinkingTo: Rcpp, RcppArmadillo, RcppParallel, RcppThread
# Suggests: doParallel, knitr, rmarkdown, testthat
# Date: 2019-07-07
# Author: Alexis Sarda-Espinosa
# Maintainer: Alexis Sarda <alexis.sarda@gmail.com>
# BugReports: https://github.com/asardaes/dtwclust/issues
# License: GPL-3
# URL: https://github.com/asardaes/dtwclust
# NeedsCompilation: yes
# SystemRequirements: C++11, GNU make
# Encoding: UTF-8
# LazyData: TRUE
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# Collate: 'CENTROIDS-dba.R' 'CENTROIDS-pam.R' 'CENTROIDS-sdtw-cent.R' 'CENTROIDS-shape-extraction.R' 'CLUSTERING-all-cent2.R' 'CLUSTERING-compare-clusterings.R' 'CLUSTERING-cvi-evaluators.R' 'CLUSTERING-ddist2.R' 'CLUSTERING-partitional-fuzzy.R' 'CLUSTERING-repeat-clustering.R' 'CLUSTERING-tadpole.R' 'CLUSTERING-tsclust-controls.R' 'CLUSTERING-tsclust.R' 'DISTANCES-dtw-basic.R' 'DISTANCES-dtw-lb.R' 'DISTANCES-dtw2.R' 'DISTANCES-gak.R' 'DISTANCES-lb-improved.R' 'DISTANCES-lb-keogh.R' 'DISTANCES-sbd.R' 'DISTANCES-sdtw.R' 'GENERICS-cvi.R' 'S4-Distmat.R' 'S4-PairTracker.R' 'S4-SparseDistmat.R' 'S4-tsclustFamily.R' 'S4-TSClusters-classes.R' 'S4-TSClusters-methods.R' 'SHINY-interactive-clustering.R' 'SHINY-ssdtwclust.R' 'SHINY-utils.R' 'UTILS-as-methods.R' 'UTILS-compute-envelope.R' 'UTILS-data.R' 'UTILS-expressions.R' 'UTILS-globals-internal.R' 'UTILS-nccc.R' 'UTILS-reinterpolate.R' 'UTILS-rng.R' 'UTILS-tslist.R' 'UTILS-utils.R' 'UTILS-zscore.R' 'pkg.R'
# Packaged: 2019-07-06 23:26:53 UTC; oso
# Repository: CRAN
# Date/Publication: 2019-07-07 04:30:02 UTC
