travis:
  secure:
    BINSTAR_TOKEN: fG68JZSHGr0mwgbGf7041MEOVStO0aely2Qbpdgx1jVWahnE9nGG7JqVWVfEfBD3Cm8P1d9o+hfn3T+2UOU+wsuIjGd+EQ95QyA0Yzh1d+zEOVz4Umm/Iv5BGNevN6QH3V7FZ4cGbM/nutuxP4C/DSftvCTl7TJv2SeLRO0EIIv+t1suN+O4bd8uUG2HgLy+R1SeCh5KPOr5/KsK5tEm56mJua7N38kgJt1SWwhzRPem+Az6MWnNiml9/wKnKVnYy86bKRDSYnG2+/NRdx0wlCeWKTL+OD5MuGoip89XU2Z3hq1DoqZR+l9ea3TyaJXqWk1cCakcUT1fKFjh4a4QXKWxt2p+wr1J83MMfL/LGZBF2FXs2xlj7LQZw3W8+DCHWGStNR42CIONN2nLg9i2gaTbNN/E/BFOCYfr7/DvU/fs4SVIYF/M4VUieAXnxEo0xKKGq/CxgbYdfY99XikpRsJvyZXtEOjTysseL/yOZIKAWDnc5EDCDEJb3in365mQO+2VOqIOz53o2J4jinSEykuWIR+0yD5TG0jdPrmoLgouupsTEOQw25jCBYJKD3xsAa541bGqtEECgKaMz9QtA54/oFYqBp0VFVfPI7qWLbkYVJwuK3O9LdKSJn0L5boOmxmGb5y7vJWsW0+uviHQNJ63+t350941ddHS7pkOj/M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
